### PR TITLE
Install markdown-it-social-mention

### PR DESCRIPTION
**Pull request by alienlebarge**
### Description

Currently, `markdown-it-regexp`with a custom regex is used to convert social handle to HTML
See #176 and #177

### Ask

@paulrobertlloyd released a 🎉 markdown-it plugin that does the same. Let's test it.

### To Do

- [x] Uninstall [markdown-it-regexp](https://www.npmjs.com/package/@gerhobbelt/markdown-it-regexp)
- [x] Install [markdown-it-social-mention](https://github.com/paulrobertlloyd/markdown-it-social-mention) from the GitHub repo
- [ ] Install the plugin from npmjs

### Additional Info

https://github.com/paulrobertlloyd/markdown-it-social-mention/issues/1

### CODE REVIEW

**Comment by alienlebarge** [comment]
Getting some error after installing it

```
alienlebargech-v3 features/install-markdown-it-social-mention npm run watch                                                                                            20:06:02

> alienlebarge.ch@3.0.0 watch
> concurrently -c "auto" "npm:watch:*"

[files]
[files] > alienlebarge.ch@3.0.0 watch:files
[files] > eleventy --config=lib/eleventy.config.js --serve
[files]
[files] [11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[files] [11ty] 1. Error in your Eleventy config file 'lib/eleventy.config.js'. You may need to run `npm install`. (via EleventyConfigError)
[files] [11ty] 2. Cannot find module 'markdown-it-social-mention'
[files] [11ty] Require stack:
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/lib/markdown.config.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/lib/eleventy.config.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Util/Require.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateConfig.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/EleventyExtensionMap.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateData.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Eleventy.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/cmd.js (via Error)
[files] [11ty]
[files] [11ty] Original error stack trace: Error: Cannot find module 'markdown-it-social-mention'
[files] [11ty] Require stack:
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/lib/markdown.config.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/lib/eleventy.config.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Util/Require.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateConfig.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/EleventyExtensionMap.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateData.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Eleventy.js
[files] [11ty] - /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/cmd.js
[files] [11ty]     at Module._resolveFilename (node:internal/modules/cjs/loader:1053:15)
[files] [11ty]     at Module._load (node:internal/modules/cjs/loader:898:27)
[files] [11ty]     at Module.require (node:internal/modules/cjs/loader:1120:19)
[files] [11ty]     at require (node:internal/modules/helpers:112:18)
[files] [11ty]     at /Users/cedricaellen/Projects/alienlebargech-v3/lib/markdown.config.js:32:5
[files] [11ty]     at Object.<anonymous> (/Users/cedricaellen/Projects/alienlebargech-v3/lib/markdown.config.js:54:3)
[files] [11ty]     at Module._compile (node:internal/modules/cjs/loader:1239:14)
[files] [11ty]     at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
[files] [11ty]     at Module.load (node:internal/modules/cjs/loader:1096:32)
[files] [11ty]     at Module._load (node:internal/modules/cjs/loader:935:12)
[files] npm run watch:files exited with code 1
```

It looks like something is missing in `node_modules/markdown-it-social-mention`
``` bash
node_modules/markdown-it-social-mention
.
├── LICENSE
├── README.md
├── lib
│   └── replace.js
└── package.json
```

**Comment by paulrobertlloyd** [comment]
Hmm, I thought index.js was included by default, but perhaps that gets overridden if you explicitly define `files` and don’t include a value for `main` in the package.json. Will update!

**Comment by paulrobertlloyd** [comment]
Try it now. I’m going to install it on my own site this evening too.

**Comment by alienlebarge** [comment]
Get errors. Have to investigate.
```
[files] > alienlebarge.ch@3.0.0 build:files
[files] > eleventy --config=lib/eleventy.config.js --quiet
[files]
[files] [11ty] Problem writing Eleventy templates: (more in DEBUG output)
[files] [11ty] 1. Having trouble rendering liquid template ./src/articles/2008/04/la-drague-a-5-ans/index.md (via TemplateContentRenderError)
[files] [11ty] 2. Cannot read properties of undefined (reading 'type') (via TypeError)
[files] [11ty]
[files] [11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'type')
[files] [11ty]     at module.exports (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdown-it-social-mention/lib/replace.js:13:21)
[files] [11ty]     at Array.<anonymous> (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdown-it-social-mention/index.js:18:43)
[files] [11ty]     at Core.process (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdown-it/lib/parser_core.js:54:13)
[files] [11ty]     at MarkdownIt.parse (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdown-it/lib/index.js:524:13)
[files] [11ty]     at MarkdownIt.render (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdown-it/lib/index.js:544:36)
[files] [11ty]     at /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Engines/Markdown.js:79:38
[files] [11ty]     at async Template._render (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateContent.js:507:22)
[files] [11ty]     at async Template.renderWithoutLayout (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Template.js:456:27)
[files] [11ty]     at async TemplateMap.populateContentDataInMap (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateMap.js:585:39)
[files] [11ty]     at async TemplateMap.cache (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateMap.js:479:5)
[files] [11ty] Copied 10 files / Wrote 0 files in 8.20 seconds (v2.0.0)
[files] npm run build:files exited with code 1
```

**Comment by alienlebarge** [comment]
Apparently, if I remove `date: YYYY-MM-dd` in frontmatter, it works

**Comment by alienlebarge** [comment]
I have updated to the last version and still get an error.
```
> alienlebarge.ch@3.0.0 build
> concurrently -c "auto" "npm:build:*"

[files]
[files] > alienlebarge.ch@3.0.0 build:files
[files] > eleventy --config=lib/eleventy.config.js --quiet
[files]
[files] [11ty] Problem writing Eleventy templates: (more in DEBUG output)
[files] [11ty] 1. Having trouble rendering liquid template ./src/articles/2008/04/la-drague-a-5-ans/index.md (via TemplateContentRenderError)
[files] [11ty] 2. Cannot read properties of undefined (reading 'type') (via TypeError)
[files] [11ty]
[files] [11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'type')
[files] [11ty]     at module.exports (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdown-it-handle/lib/replace.js:13:33)
[files] [11ty]     at Array.<anonymous> (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdown-it-handle/index.js:16:41)
[files] [11ty]     at Core.process (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdown-it/lib/parser_core.js:54:13)
[files] [11ty]     at MarkdownIt.parse (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdown-it/lib/index.js:524:13)
[files] [11ty]     at MarkdownIt.render (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/markdown-it/lib/index.js:544:36)
[files] [11ty]     at /Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Engines/Markdown.js:79:38
[files] [11ty]     at async Template._render (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateContent.js:507:22)
[files] [11ty]     at async Template.renderWithoutLayout (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Template.js:456:27)
[files] [11ty]     at async TemplateMap.populateContentDataInMap (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateMap.js:585:39)
[files] [11ty]     at async TemplateMap.cache (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateMap.js:479:5)
[files] [11ty] Benchmark    589ms   9%   982× (Configuration) "slugify" Nunjucks Filter
[files] [11ty] Copied 10 files / Wrote 0 files in 5.88 seconds (v2.0.0)
[files] npm run build:files exited with code 1
```

**Comment by paulrobertlloyd** [comment]
Hmmm, will have another look. Out of interest, if you remove the first HTML `img` tag from the `la-drague-a-5-ans` post, does that prevent the issue from happening at all?

**Comment by alienlebarge** [comment]
Apparently I got files with [`sp`](https://www.asciihex.com/character/punctuation/32/0x20/sp-space) char that were problematic. I replaced theme with a standard space char

**Comment by alienlebarge** [comment]
I keep the PR open until the lpugin is release on npmjs

**Comment by paulrobertlloyd** [comment]
Oh, nice! I’ve gotten caught out by special characters a number of times, always a pain when that happens.

I’ll publish the package this evening. 🎉

**Pull request merged**
